### ISSUE TITLE
Pod install use_frameworks!

### ISSUE THREAD

**Issue by OliverZiegler** [scalessec/Toast-Swift#1]
Installing Toast-Swift via Cocoapods results in errors.

This is the module `Toast_Swift` after installing with `use_frameworks!` needed for Swift
````swift
import ObjectiveC
import Toast_Swift
import Toast_Swift.Swift
import UIKit

public var Toast_SwiftVersionNumber: Double
````

As you can see the module references itself...

Is this a bug or am I doing something wrong?

**Comment by scalessec** [comment]
It's a bug. Sorry about that. Feel free to send a pull request if you can fix it, otherwise I'll try to get to it this week.

**Comment by dasoga** [comment]
Hi!
Any update for this?. When I install it via Cocoapods I can't use the library.
I wanted to fix it, but I could.

**Comment by OliverZiegler** [comment]
I really tried to fix this issue but did not succeed. 

The following points I found:
* `import ObjectiveC` in Toast.swift is not necessary
* Self reference seems to be normal with installation via Cocoapods
* The interface of Toast.swift is completely missing in the module (there should be included all the public method definitions)

@scalessec has installing via cocoa pods ever worked? (build is working but not using the library)

**Comment by craigpearce5** [comment]
Does this issue seem to be with cocoapods?  Can it be used by installing manually?

**Comment by OliverZiegler** [comment]
Its kind of a bug when installing via cocoapods. 
If you manually download and import into your project everything works (I currently use it like this)
