### ISSUE TITLE
iPhone X issue

### ISSUE THREAD

**Issue by sudhanshutil** [scalessec/Toast-Swift#100]
Toast with  position as 'CSToastPositionTop' is not displaying it in 'safeArea'. It is covered by the speaker line of iPhone X. 
![toast cstoastpositiontop](https://user-images.githubusercontent.com/11748454/38407482-3e9d7c24-3997-11e8-8237-247eb85039c3.png)

**Comment by scalessec** [comment]
This is your responsibility to position the toast where you want it, not the library's. A toast can be presented in any view in the hierarchy, not just `self.view`. This adjustment only makes sense for this one use-case one one device model and therefore should be handled by you.
