### ISSUE TITLE
View init - Not on Main Thread

### ISSUE THREAD

**Issue by x-NR-x** [scalessec/Toast-Swift#104]
<img width="1050" alt="screen shot 2018-05-31 at 5 15 45 pm" src="https://user-images.githubusercontent.com/5113371/40787648-c9a033d6-64f6-11e8-926a-2f42f96aaf36.png">

**Comment by scalessec** [comment]
100% of all the code in `Toast-Swift` is on the main thread. This is an error in your code. Looks like your code is trying use `Toast-Swift` inside of an `NSOperationQueue` off the main thread and that is not allowed by `UIKit`.
