### ISSUE TITLE
error: Abort trap: 6 in swift 4.2

### ISSUE THREAD

**Issue by waqarv712** [scalessec/Toast-Swift#106]

**Comment by scalessec** [comment]
Stack trace?

**Comment by waqarv712** [comment]
I'm using Xcode 10 and swift 4.2
![screen shot 2018-06-11 at 8 17 07 pm](https://user-images.githubusercontent.com/28779393/41240640-736b4fac-6db4-11e8-85bb-8a3c8e60c4a0.png)

**Comment by scalessec** [comment]
If you choose `Clean` from Xcode's `Product` menu, and then hold `option` and select `Clean Build Folder` from the `Product` menu (you must be holding option), does that work?

**Comment by waqarv712** [comment]
No, it's not working.

**Comment by scalessec** [comment]
Full support for Xcode 10 & Swift 4.2 is now available in tag `4.0.0` thanks to #112.
