### ISSUE TITLE
Toast is always displayed in the bottom

### ISSUE THREAD

**Issue by ArtemBogush** [scalessec/Toast-Swift#107]
Seems like position is ignored and toast is always displayed in the bottom:

self.view.makeToast(message, duration: 3.0, position: .top);

Is there anything I can do to show it in center or on top?

pod 'Toast-Swift', '3.0.1'
swift 4.1
Xcode 9.3.1

**Comment by scalessec** [comment]
Works fine the sample project so I don't believe this is an issue with the library.
