### ISSUE TITLE
MessageView Not stick to position in UITableViewController 

### ISSUE THREAD

**Issue by d33pak-s1ngh** [scalessec/Toast-Swift#108]
Following code I am using to Display No internet connection message in a UITableViewController when user scrolls tableView the messageView appears to be scroll with it. instead of stick to bottom it moves with tableview.

```
if !Connectivity.isConnectedToInternet {
            self.view.makeToast("Please Connect to Internet.", duration: 2.0, position: .bottom, title: "No Internet", image: nil)

            return
        }
```

**Comment by scalessec** [comment]
Please check the open issues before opening a new issue. I answered this in #20 and #91.
