### ISSUE TITLE
Xcode 10 GM seed (Swift 4.2)

### ISSUE THREAD

**Issue by maximzhemerenko** [scalessec/Toast-Swift#113]
Hi, thanks for this library! One issue: I cannot use it with Xcode 10 GM seed. Are there any solution to proceed?

**Comment by scalessec** [comment]
Full support for Xcode 10 & Swift 4.2 is now available in tag `4.0.0` thanks to #112.

**Comment by maximzhemerenko** [comment]
Thanks you for quick response!
