### ISSUE TITLE
Argument labels (style:) do not match ant available overloads

### ISSUE THREAD

**Issue by TopeMateo** [scalessec/Toast-Swift#114]
Hello, you guys recently pushed 4.0 on Toast. I'm using 3.0.1 before. It was working fine. Here is the error:
1) Argument labels (style: ) do not match any available overloads (on Pods/Toast-Swift/Toast/Toast.swift)
let activityIndicatorView = UIActivityIndicator(style: .whiteLarge)

2) type RunLoopMode has no member common (on Pods/Toast-Swift/Toast/Toast.swift)
RunLoop.main.add(timer, formode: .common)

I reverted back on version 3.0.1. Hope you guys can fix this

**Comment by scalessec** [comment]
`4.0.0` requires Xcode 10 and Swift 4.2.
