### ISSUE TITLE
.swift-version not in 4.2

### ISSUE THREAD

**Issue by JohanDufau** [scalessec/Toast-Swift#117]
Hello,

There is a small issue in your .swift-version file (https://github.com/scalessec/Toast-Swift/blob/master/.swift-version). It does not indicate v4.2 whereas the pod uses swift 4.2.

Cocoapods relies on this file for the SWIFT_VERSION flag. That creates issues when building this pod as a dependency with Xcode 10.

Thank you!

**Comment by scalessec** [comment]
Interesting.. I personally don't use Cocoapods so I miss these issues. If I bump the version and re-tag `4.0.0` would that fix it?

**Comment by JohanDufau** [comment]
Yeah, totally. If you simply set 4.2 in this file and update the pod, it will fix :)

**Comment by scalessec** [comment]
Done. Let me know if that fixes it. Thanks for your help!

**Comment by JohanDufau** [comment]
Thanks! I confirm it fixes the issue. Thanks for the reactivity :)
