### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by FranDepascuali** [scalessec/Toast-Swift#118]
Hey there! Thanks for this library!

I've found a memory leak while using `Toast-Swift`. My code is the following:

```swift
class MyViewController {

    override func viewDidLoad() {
        ...
        viewModel
        .showToast
        .observe(on: UIScheduler())
        .startWithValues { [unowned self] (toastEvent, orientation) in
            self.view.hideAllToasts(clearQueue: true)
            if case .show(let scanToast) = toastEvent {
                self.view.show(toast: scanToast, orientation: orientation)
            }
    }
    }
}
```
I'm using `ReactiveSwift`, but the memory leak comes from the `showToast` that ends up being called `view.showToast(toastView, duration: toast.duration)` (I've tested all of this). The toast is retaining the presenting view (I suspect that it is related with the usage of `OBJC_ASSOCIATION_RETAIN_NONATOMIC` in this lib).

The way of solving this memory leak (really hard to find) was doing this:
```swift
    deinit {
        // Note: There is in which the toast stays alive, retaining this view.
        // Therefore we have to hide all toast for view to be deallocated correctly.
        view.hideAllToasts(clearQueue: true)
    }
```

### Steps to reproduce: 

- Present a `UIViewController` modally (via `present`)
- Show a toast
- Dismiss the `UIViewController`
- you will see in memory that the view which presents the toast is still there (even though the `UIViewController` was deallocated).

## Screenshot of this bug
![screen shot 2018-09-25 at 14 34 06](https://user-images.githubusercontent.com/12101394/46031765-39305700-c0d0-11e8-803b-625f8612e11e.png)

## Screenshot with hideAllToasts in ViewController's deinit
![screen shot 2018-09-25 at 14 33 19](https://user-images.githubusercontent.com/12101394/46031754-2f0e5880-c0d0-11e8-9ec4-2bfdb4443fab.png)

**Comment by scalessec** [comment]
Hey @FranDepascuali, thanks for the detailed notes on this issue. Following your instructions, I just performed some tests myself, and I can confirm that this is **not**, in fact, a memory leak. The view is released once the timer on the toast completes. I agree that this is not ideal, so I'll revisit this when I have some time so see if there's a more optimal solution. Ultimately though, the memory is released without leaking and if you're really concerned you can always call `hideAllToasts` in your controller's `deinit` to free the memory immediately.

Here's the code I used to confirm:
```swift
class TestView: UIView {
    deinit {
        print("view deinit")
    }
}

class TestController: UIViewController {
    deinit {
        print("view controller deinit")
    }
    
    override func loadView() {
        let test = TestView()
        test.backgroundColor = .blue
        self.view = test
    }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        let closeButton = UIButton(frame: CGRect(x: 50.0, y: 200.0, width: 100.0, height: 44.0))
        closeButton.setTitle("CLOSE", for: .normal)
        closeButton.addTarget(self, action: #selector(handleClose), for: .touchUpInside)
        self.view.addSubview(closeButton)
        
        let showButton = UIButton(frame: CGRect(x: 50.0, y: 300.0, width: 100.0, height: 44.0))
        showButton.setTitle("SHOW", for: .normal)
        showButton.addTarget(self, action: #selector(handleShow), for: .touchUpInside)
        self.view.addSubview(showButton)
    }
    
    @objc
    private func handleClose() {
        self.dismiss(animated: true)
    }
    
    @objc
    private func handleShow() {
        self.view.makeToast("hello world", duration: 5.0)
    }
}

// in some other view controller
self.present(TestController(), animated: true)
```
