### ISSUE TITLE
toast with Segue

### ISSUE THREAD

**Issue by nishantroy** [scalessec/Toast-Swift#12]
For a login page, I want to show the toast while segue-ing to the next ViewController. How can I do this?

Thanks.
Nishant

**Comment by scalessec** [comment]
Instead of presenting the toast in `self.view` present the toast in `self.navigationController.view`, then the toast will remain present when you push a new view controller onto the stack.

**Comment by nishantroy** [comment]
```
self.navigationController!.view.makeToast("Logged in!", duration: 3.0, position: .Bottom)
                    
self.performSegueWithIdentifier("loginSuccessful", sender: nil)
```

When I run this^, it briefly shows the toast (barely half a second), then segues and it disappears.

**Comment by scalessec** [comment]
Hmm, is there no parent view you can present it in? You could also use `self.view.window`. It's not ideal, but it'll work.

**Comment by nishantroy** [comment]
Thanks! Just one more thing. Is there a way to set duration for makeToastActivity? Can I have the spinner appear while firebase is being contacted to authorize user?

**Comment by scalessec** [comment]
You have to explicitly call `hideToastActivity()` when you request completes. Depending on your user's network conditions, there's no way to determine how long that request is going to take. So you need to call it explicitly after the request finishes.
