### ISSUE TITLE
fit the width of screen

### ISSUE THREAD

**Issue by JafarKhoshtabiat** [scalessec/Toast-Swift#120]
I'm trying to fit toast to the screen width. this is my code:

var myStyle = ToastStyle()
myStyle.activitySize.width = self.view.frame.size.width
        
self.view.makeToast(message, duration: 2.0, position: .top, title: "Message Title", image: nil, style:      myStyle, completion: nil)

but it doesn't work. can anyone help me with this?

**Comment by scalessec** [comment]
Going forward, please use StackOverflow for these types of questions. 

`activitySize` only works with `makeToastActivity`, not `makeToast`. `makeToast` always uses dynamic sizing based on the content you are presenting (constrained by `maxWidthPercentage` and `maxHeightPercentage`). If you want to present toast with a static size (eg: the size of your superview), you need to make your own `UIView` subclass` with its frame set the way you want and then you can present it using `showToast`.
