### ISSUE TITLE
Errors While Migrating To Swift 4.2

### ISSUE THREAD

**Issue by baquer** [scalessec/Toast-Swift#122]
These Errors are occurring while migrating to swift 4.2
1 :- init(activityIndicatorStyle:)' has been renamed to 'init(style:)'
2 :- RunLoopMode' has been renamed to 'RunLoop.Mode'

**Comment by scalessec** [comment]
Please check closed issues before opening a new issue. Use the `4.0.0` tag for Swift 4.2 support. It's also clearly stated in the README.
