### ISSUE TITLE
Set Image From Url

### ISSUE THREAD

**Issue by umairali612** [scalessec/Toast-Swift#125]
Can I set image which I have url to load image from this url. I am currently using KingFisher for getting images from URL.

**Comment by kuyu12** [comment]
Hey, Toast-Swift is supporting UIImage, not URL.

You can load the image from KingFisher and then pass it to the toast.

**Comment by scalessec** [comment]
The default Toast view will not support this. You can use the `showToast` methods to show any view as toast. Just make it your own `UIView` subclass that can load an image using `Kingfisher` (if that's what works for your app) and then use `showToast` to present the view.
