### ISSUE TITLE
How to use toast in appdelegate 

### ISSUE THREAD

**Issue by isaacraja15** [scalessec/Toast-Swift#127]
Im using Corebluetooth in appdelegate so i need to display toast message bluetooth connected 

how can i use 
 i try this method 

 var visibleViewController: UIViewController?
 visibleViewController?.view.makeToast("disconnect")
but it not work.

**Comment by kuyu12** [comment]
Toast is working on UIView.

If you want to use it in the appDelegate you have to get the top view controller and then execute the toast on the view.

you can look here for func to get the top view controller - [Here](https://stackoverflow.com/questions/26667009/get-top-most-uiviewcontroller)

hope it help (:

**Comment by isaacraja15** [comment]
![screenshot 2018-11-25 at 1 26 22 am](https://user-images.githubusercontent.com/44321070/48972474-3959be00-f051-11e8-9921-9cbcdda5a92b.png)

noerror 

but it not disappear bro

**Comment by scalessec** [comment]
This is an issue with you code, not this library. Please use stackoverflow.
