### ISSUE TITLE
XCode 10.1 and Swift 4.2 fails to build

### ISSUE THREAD

**Issue by henjue** [scalessec/Toast-Swift#128]
xcode 10.1
i use   pod 'Toast-Swift', '~> 4.0.0'
but still build faild!
![g](https://user-images.githubusercontent.com/1314740/48931955-0077f700-ef34-11e8-93ce-a62a527bb114.jpg)

**Comment by abbood** [comment]
@scalessec why was this closed? i got the same error!

**Comment by scalessec** [comment]
Try `4.0.1`.

**Comment by shoaibnomani** [comment]
> Try `4.0.1`.

Still getting the errors. Why is this issue closed without being resolved?

**Comment by shoaibnomani** [comment]
> @scalessec why was this closed? i got the same error!

Did you manage to fix this somehow?

**Comment by priya836** [comment]
@shoaibnomani  do you know the fix?
