### ISSUE TITLE
Ambiguous use of 'makeToast(_:duration:position:title:image:style:completion:)'

### ISSUE THREAD

**Issue by hitesh-shukla** [scalessec/Toast-Swift#135]
Getting error
Ambiguous use of 'makeToast(_:duration:position:title:image:style:completion:)'
self.view.makeToast(message)

**Comment by mrseth01** [comment]
+1

**Comment by MorLightJ** [comment]
+1

**Comment by chaitu7979** [comment]
'makeToast(_:duration:position:title:image:style:completion:)'
