### ISSUE TITLE
Toast no disappear on application's key window at times

### ISSUE THREAD

**Issue by TuDoudong** [scalessec/Toast-Swift#140]
I know that the runloop mode of my toast is common, but toast does not disappear occasionally . Importantly, toast disappears when I slide the tableView. I don't know exactly why. I need your help, thank you

**Comment by asifhabib** [comment]
If you are using very old mac or very low graphics and checking this in simulator, then this issue might arise. Get new/good mac or test on real device.

**Comment by TuDoudong** [comment]
Thank you for your answer, but I use iPhone6 and the mobile phone system is iOS12. When I was not connected to the mobile phone and Xcode to debug, I continuously operated the page to show toast for much times and occasionally toast did not disappear. This situation is not easy to duplicate
