### ISSUE TITLE
Issue when we have tabbar controller with center button position is up

### ISSUE THREAD

**Issue by mendaparadarshit** [scalessec/Toast-Swift#145]
![Screenshot 2019-06-28 at 10 49 24 AM](https://user-images.githubusercontent.com/11643853/60318946-780e7880-9992-11e9-8e40-f607c248aefe.png)

Please check this screenshot,  Toast showing underneath of center button and there is no property to put margin from the bottom

**Comment by scalessec** [comment]
You can calculate the position yourself using a center point for the toast.
