### ISSUE TITLE
SPM Support

### ISSUE THREAD

**Issue by waterskier2007** [scalessec/Toast-Swift#147]
Have there been any thoughts around adding support for Swift Package Manager?

**Comment by SAPIENTechnologies** [comment]
I see there is a PR for SPM support. When can we expect that to be committed to the main branch?

**Comment by scalessec** [comment]
I'll make it a priority to get that merged within the next few days. Thanks for the reminder.

**Comment by SAPIENTechnologies** [comment]
Thanks!

**Comment by scalessec** [comment]
Version `5.0.1` with SPM now available thanks to #155.  Please try it and let me know if you have any issues.
