### ISSUE TITLE
Close a toast if new toast appears on same screen.

### ISSUE THREAD

**Issue by NikhilGangurde** [scalessec/Toast-Swift#148]
Hello, 
I am developing an app in which I have you used this repo and I want that if the toast is present on view it should close and the new one should appear.
what can I do for this?

**Comment by dnorton29** [comment]
The simplest was is to just call `self.view.hideToasts()` before displaying your toast. If you need something more automatic, you're going to need to fork and modify the code to do this.

**Comment by NikhilGangurde** [comment]
so do I have to write `self.view.hideToasts()` each time new toast display's.

there are lot of toast already written in project.

**Comment by dnorton29** [comment]
Pretty much or just do like I suggested and modify the code manually so that each `makeToast()` call internally calls `hideAllToasts()`. The code base is small, so it should be relatively easy to implement.

**Comment by NikhilGangurde** [comment]
ok
