### ISSUE TITLE
Possible to use in Objective C?

### ISSUE THREAD

**Issue by neobie** [scalessec/Toast-Swift#153]
Now that the Objective C version of Toast is not maintained and having bug in iOS 13,
is it possible to use Toast-Swift in objective C?
I have created header and import "Toast_Swift-Swift.h", but the makeToast interface simply cannot be found.

**Comment by scalessec** [comment]
This project will work in Objective-C, but the Objective-C project is still being maintained and works as expected on iOS 13.
