### ISSUE TITLE
Accessibility for vision-impaired

### ISSUE THREAD

**Issue by jimmynotjames** [scalessec/Toast-Swift#159]
Would be lovely to have some accessibility features built in. 

Right now, in the app I'm working on, I do a 'purchase successful' message but I have to do this:

```
    view.makeToast(message, duration: 10000.0, position: .center)
    UIAccessibility.post(notification: .screenChanged, argument: message)

```

It would be lovely if this were encapsulated in the library itself. Also, the above thing doesn't set the Accessibility Label or Value in a way that it's clear that the thing can be dismissed by tapping on it, though I would hope vision-impaired folks might be used to how that works. I'm also not clear on how a blind person would know that I placed it centered on the screen, alas. 

Maybe I missed this part, but I couldn't find a way to retrieve the UIView of a currently-displayed toast (or the last one displayed, if multiple). I totally get why that would be a private property, but if I could get that, I potentially could do some accessibility things using that, though that seems a bit hacky to me.

**Comment by scottsymes** [comment]
Plus 1 to this.

**Comment by scalessec** [comment]
Sorry for the delay. Added to the upcoming `5.1.0` release.
