### ISSUE TITLE
SPM 

### ISSUE THREAD

**Issue by syedrazackimran** [scalessec/Toast-Swift#165]
I'm trying to add SPM. but I gotta issues with it kindly help me to resolve it

"https://github.com/terwanerik/Toast-Swift.git"

Showing All Messages
: The repository could not be found. Make sure a valid repository exists at the specified location and try again.

**Comment by scalessec** [comment]
You have the wrong url. Should be:


https://github.com/scalessec/Toast-Swift.git

**Comment by syedrazackimran** [comment]
I put below repository also still I'm getting same issues
<img width="732" alt="Screenshot 2020-06-29 at 5 16 32 PM" src="https://user-images.githubusercontent.com/15051045/86001272-49efc880-ba2c-11ea-8330-06f7d9661b77.png">


"https://github.com/scalessec/Toast-Swift.git"

**Comment by bestK** [comment]
use `git@github.com:scalessec/Toast-Swift.git`

https://stackoverflow.com/questions/58165880/xcode-11-spm-authentication-failed-because-no-credentials-provided
