### ISSUE TITLE
SwiftPM still Not working

### ISSUE THREAD

**Issue by syedrazackimran** [scalessec/Toast-Swift#166]
I put below the repository also still I'm getting the same issues. check be below screen shots. Kindly do needfully

<img width="732" alt="Screenshot 2020-06-29 at 5 16 32 PM" src="https://user-images.githubusercontent.com/15051045/86001272-49efc880-ba2c-11ea-8330-06f7d9661b77.png">

"https://github.com/scalessec/Toast-Swift.git"

_Originally posted by @syedrazackimran in https://github.com/scalessec/Toast-Swift/issues/165#issuecomment-651063128_

**Comment by vincentthe0ne** [comment]
Just tried it and it works for me ATM.
Here's my line in the Package.swift File:

`       
     .package(name: "Toast", url: "https://github.com/scalessec/Toast-Swift.git", from: "5.0.0")
`

**Comment by syedrazackimran** [comment]
> Just tried it and it works for me ATM.
> Here's my line in the Package.swift File:
> 
> ` .package(name: "Toast", url: "https://github.com/scalessec/Toast-Swift.git", from: "5.0.0")`

first, I tried to install Version 5.0.1 then I saw your reply then I change to version 5.0.0. Still, I'm facing issues. kindly help me to resolve it.

**Comment by syedrazackimran** [comment]
Here I added video. what I am done check it once.

[https://streamable.com/ajdvd1](url)

**Comment by syedrazackimran** [comment]
Sorry, I Reset Package cache and delete Dervieddata. then it's working fine. Thanks.
