### ISSUE TITLE
You can use "typealias" instead of "ToastCompletionWrapper"

### ISSUE THREAD

**Issue by FunnyerFeng** [scalessec/Toast-Swift#184]
You can use:
typealias completion = ((Bool) -> Void)?
instead of:
private class ToastCompletionWrapper {
        let completion: ((Bool) -> Void)?
        
        init(_ completion: ((Bool) -> Void)?) {
            self.completion = completion
        }
    }

**Comment by scalessec** [comment]
The `objc_setAssociatedObject` API requires the associated object to be a  class, so unfortunately simply using a typealias for the completion closure does not work.
