### ISSUE TITLE
Toast is getting shown behind the view controller

### ISSUE THREAD

**Issue by nishchal-v** [scalessec/Toast-Swift#185]
when you show a toast and navigate to another view controller the toast is overshadowed by navigating view controller

**Comment by TJRoger** [comment]
You should handle this case yourself. e.g. You can hide all toast in that view first before navigating to another view controller,

**Comment by ubuntudroid** [comment]
Just use your `UIView`'s `parent.view` or even better `UINavigationController.view` to render the toast. Then it will stay visible across navigation.
