### ISSUE TITLE
'ToastStyle' cannot be constructed because it has no accessible initializers

### ISSUE THREAD

**Issue by LucisBaoshg** [scalessec/Toast-Swift#19]
'ToastStyle' cannot be constructed because it has no accessible initializers

Xcode 7.3

**Comment by williamkurniawan** [comment]
Same here

Screenshot:
<img width="808" alt="screen shot 2016-04-24 at 12 35 29 pm" src="https://cloud.githubusercontent.com/assets/16736202/14765744/38983c24-0a19-11e6-8010-0a6e3e194f35.png">

**Comment by scalessec** [comment]
Sorry about that guys. This is fixed in 1.3.0 and in master.
