### ISSUE TITLE
Toast should move up with keyboard

### ISSUE THREAD

**Issue by shadowpath** [scalessec/Toast-Swift#193]
Showing a toast on the main view of a controller makes it invisible if keyboard is showing. Should account for keyboard height and move it if the keyboard is showing and move back down once closed.

**Comment by vijaycoderkube** [comment]
I'm also facing this issue, Any update?

**Comment by abbasnaqvi200** [comment]
let windows = UIApplication.shared.windows
windows.last?.makeToast("toast message")
