### ISSUE TITLE
Xcode 15.2 Compiler Warning: Forming 'UnsafeRawPointer' to an inout variable  ...

### ISSUE THREAD

**Issue by moshuqi** [scalessec/Toast-Swift#212]
Hi:

There is a compilation warning in Xcode 15.2：
Forming 'UnsafeRawPointer' to an inout variable of type String exposes the internal representation rather than the string contents.
![1706330449101](https://github.com/scalessec/Toast-Swift/assets/3349958/7c7c5413-6e6b-4ce0-a8cf-3ba4e2dfebea)

**Comment by scalessec** [comment]
This was fixed in `5.1.0`.
