### ISSUE TITLE
ToastActivity never gone

### ISSUE THREAD

**Issue by DamonChen117** [scalessec/Toast-Swift#23]
Call make makeToastActivity and hideToastActivity frequently in pairs. And ToastActivity never disappear.

In func hideToastActivity,  the below codes should be moved before the call of UIView.animateWithDuration.
`objc_setAssociatedObject(self, &ToastKeys.ActivityView, nil, .OBJC_ASSOCIATION_RETAIN_NONATOMIC)`

**Comment by arange** [comment]
I've tried to move that codes before UIView.animate(withDuration:) called, but nothing happenes.
Is there anything else to do except this?

**Comment by DamonChen117** [comment]
Hi arange, 
1. Don't forget to call hideToastActivity
2. Try my fork and see if it has been fixed. [DamonChen117/Toast-Swift](https://github.com/DamonChen117/Toast-Swift) 
github "DamonChen117/Toast-Swift" ~> 1.3.1

If the issue is still there, maybe it's a different issue.

**Comment by scalessec** [comment]
Fixed on `master`.
