### ISSUE TITLE
Toast showing mode

### ISSUE THREAD

**Issue by danielaRiesgo** [scalessec/Toast-Swift#25]
Hello ! I've been using the framework at work, and I really like it, but I run into the issue that I needed it to hide a toast programmatically and there was no possibility for that. There is a private hide toast method; is there any particular reason why you decided to make it private, or just didn't feel the need to make it public?

The situation was that we didn't want a queue of toasts and neither toasts overlapping. I think it would be great to have a "mode" were you can choose from queue, "normal" (showing one on top of the other) and "unique" (a view can show one toast at a time). I think it could be done, for example, by storing in the view the lastToast shown (as a UIView?) and hide the lastToast before showing a new one and updating the property.

But apart from having a mode option for unique toast showing, I think having the public hideToast method can give the programmer more flexibility for the exceptional case they run into.

What do you think?

**Comment by scalessec** [comment]
I'd prefer to just make `hideToast(_:)` public. One of the reasons I never made this public in the first place because it requires a reference to the toast view, which is a little inconvenient because none of the stock `makeToast` methods return a reference to the view they create. If you're present your own custom view as toast, this isn't a big deal. However if you were using `makeToast`, then it requires you to manually call `toastViewForMessage` to get the reference to the view, and then `showToast(_:)`.

So, in the interim, I'll release a new version this week that just makes the existing `hideToast(_:)` method public. Ultimately though I want to think about how we can elegantly create a `hideToast()` method that doesn't require a reference to the toast view. This would be the ideal solution.

**Comment by scalessec** [comment]
In addition, I may consider merging this into both Objective-C and Swift versions: https://github.com/scalessec/Toast/pull/81

**Comment by danielaRiesgo** [comment]
And what do you think of adding something like this in the framework?

In UIView's public extension:
```
private var currentToast: UIView?

public func hideToast() {
    if let currentToast = currentToast {
         if let timer = objc_getAssociatedObject(toast, &ToastKeys.Timer) as? NSTimer {
            timer.invalidate()
        }
        self.hideToast(toast, fromTap: true)
    }
}
```

And in `makeToast` method:
```
public func makeToast(message: String?, duration: NSTimeInterval, position: ToastPosition, title: String?, image: UIImage?, style: ToastStyle?, completion: ((didTap: Bool) -> Void)?) {
        var toastStyle = ToastManager.shared.style
        if let style = style {
            toastStyle = style
        }
        
        do {
            currentToast = try self.toastViewForMessage(message, title: title, image: image, style: toastStyle)
            self.showToast(currentToast, duration: duration, position: position, completion: completion)
        } catch ToastError.InsufficientData {
            print("Error: message, title, and image are all nil")
        } catch {}
    }
```

Add `currentToast = nextToast` and else clause in the hideToast method:
```
private func hideToast(toast: UIView, fromTap: Bool) {
        ....
            
            if let nextToast = self.queue.firstObject as? UIView, duration = objc_getAssociatedObject(nextToast, &ToastKeys.Duration) as? NSNumber, position = objc_getAssociatedObject(nextToast, &ToastKeys.Position) as? NSValue {
               currentToast = nextToast
                self.queue.removeObjectAtIndex(0)
                self.showToast(nextToast, duration: duration.doubleValue, position: position.CGPointValue())
            } else {
                currentToast = .None
            }
        }
    }
```

I don't know if I'm missing anything.

**Comment by AIsaac08** [comment]
Is this still open? 🤔

**Comment by eyzuky** [comment]
I figured a neat and easy to implement solution for this without you needing to change the API at all.
What I thought about (and tested and got it working perfectly) is to add the Toast to a different view, and when I want to hide the toast I simply remove the view from its superview and the Toast is removed along with it. Then If another toast needs to be displayed, I simply initialize the same view again and it is a clean view and then there is no toasts left. Some basic sample code:
```
    var viewForToast = UIView()
    func showToast(result: String) {
        self.viewForToast.removeFromSuperview()
        viewForToast = UIView()
        viewForToast.frame = self.view.frame
        
        self.viewForToast.makeToast(result, duration: 10.0, position: .center)
        self.view.addSubview(viewForToast)
    }

```

**Comment by scalessec** [comment]
I'm only a year and a half late on this, but it's now possible in `3.0.0`. You can have `ToastManager.shared.isQueueEnabled` set to `true` and then you can call `self.view.hideToast()` to immediately hide the active toast and present the next one (assuming there's multiple toasts in the queue).
