### ISSUE TITLE
Duplicate Toast Activity

### ISSUE THREAD

**Issue by eh1255** [scalessec/Toast-Swift#27]
I'm using a Toast Activity indicator to show that results are being fetched when a user type in a search bar. Every time the search text is updated, there is another call to makeToastActivity. The documentation says that only one activity view will be created, but I wind up with dozens, and calling hideToastActivity any number of times only gets rid of the top one on the stack.

I presume this is not intended behavior, but if it is, is there a way to get a reference to the activity view so I can avoid creating duplicates?

**Comment by DamonChen117** [comment]
It seems duplicate of [](https://github.com/scalessec/Toast-Swift/issues/23)

try my fork and see if it has been fixed. [](https://github.com/DamonChen117/Toast-Swift)

**Comment by scalessec** [comment]
Most likely a bug.

**Comment by MoridinBG** [comment]
It is. You are testing for ToastKeys.ActiveToast in makeToastActivity(position:), but you are setting and getting ToastKeys.ActivityView in hideToastActivity and makeToastActivity(toast:view:)

**Comment by scalessec** [comment]
Fixed on master.
