### ISSUE TITLE
Why use Associate?

### ISSUE THREAD

**Issue by DeepMissea** [scalessec/Toast-Swift#30]
Maybe It's a low-level question, but really I want to know why use the runtime, why not use computed properties?

**Comment by scalessec** [comment]
The view presenting the toast view needs to retain the toast, so a stored property is required. In fact, that's true for all the properties used in the library (they all need to be retained). Unfortunately, Swift extensions don't allow stored properties (just like Objective-C categories). Here's more details: http://stackoverflow.com/questions/25426780/how-to-have-stored-properties-in-swift-the-same-way-i-had-on-objetive-c

Closing this ticket. If I'm missing something obvious, feel free to reopen with an example.
