### ISSUE TITLE
Tag 2.0.0 is missing from CocoaPods

### ISSUE THREAD

**Issue by scalessec** [scalessec/Toast-Swift#38]
Version `2.0.0` is missing from CocoaPods, due to issues related to CocoaPods and Xcode8. As of today, `pod lib lint` fails and therefore 2.0.0 can't be published.

This is the same issue:
https://github.com/CocoaPods/CocoaPods/issues/5663

And that issue has this cause:
https://github.com/CocoaPods/CocoaPods/issues/5661

This should be fixed when the next version of Cocoapods is released.

**Comment by mtissington** [comment]
there is an rc1 out now of  CocoaPods ... and the same issue ..

**Comment by scalessec** [comment]
Hmm, that's unfortunate. I spent a few hours on this today and couldn't get it to pass. So frustrating.

**Comment by mtissington** [comment]
Any update on this? Thanks!

**Comment by golfguru1** [comment]
+1 for update

**Comment by scalessec** [comment]
Sorry, but there's no good news yet. The pod still fails to lint in CocoaPods `1.0.1`. The CocoaPods team appears to have merged the fix into `master`, but unfortunately the CocoaPods `master` branch is currently failing builds on Travis. Once it's fixed I'll clone `master`, build CocoaPods from  the source, and then lint from that build. But until them I'm stuck.

**Comment by malclarkeuk** [comment]
+1 for update

**Comment by scalessec** [comment]
You will have a pod once there's a version of CocoaPods that supports Xcode 8. Until then, we wait.

**Comment by minuscorp** [comment]
using ```pod 'Toast-Swift', :git => 'https://github.com/scalessec/Toast-Swift.git', :branch => 'master'``` solves the issue in the meantime.

**Comment by Coeur** [comment]
I made #43 for you.

**Comment by scalessec** [comment]
Fixed, thanks to @Coeur !
