### ISSUE TITLE
Imports fine into all but one view controller

### ISSUE THREAD

**Issue by bflora** [scalessec/Toast-Swift#39]
I'm really enjoying his but have hit a snag.  I have one view controller that does not seem to like Toast-Swift.  While I'm able to import Toast_Swift in 14 of my 15 view controllers, I have one where XCode tells me "Module not found".  It's perplexing.  Any idea what could be the problem?

![yob-0hot](https://cloud.githubusercontent.com/assets/543562/18613186/6a73b218-7d29-11e6-9ac8-3bccd95dd78c.png)

**Comment by scalessec** [comment]
Hmm, that's strange. Are you using CocoaPods or Carthage? Or adding manually?

**Comment by bflora** [comment]
CocoaPods.  Could there be a situation where Toast Swift doesn't like something happening in this VC?
