### ISSUE TITLE
Full width toast

### ISSUE THREAD

**Issue by marcio0** [scalessec/Toast-Swift#4]
Is there a way to make a full-width toast?

**Comment by mitchellporter** [comment]
+1

**Comment by mitchellporter** [comment]
I'm going to try and implement this using the custom view toast. Will report back.

**Comment by scalessec** [comment]
Guys, if you read through the documentation you would see that this is possible. If you look at `maxWidthPercentage` in `CSToastStyle`, it states:

> A percentage value from 0.0 to 1.0, representing the maximum width of the toast view relative to it's superview. Default is 0.8 (80% of the superview's width).

So that means you can do:

```swift
var style = ToastStyle()
style.maxWidthPercentage = 1.0
self.view.makeToast("This is a full width piece of toast", duration: 3.0, position: .Bottom, style: style)
```

If you want all pieces of toast to be full width going forward, you can just set the shared style and then you can just pass nil to `style:` param in the `makeToast` methods. For example:

```swift
// the full width style we created above
ToastManager.shared.style = style

// now all toasts will be full width going forward, without needing to provide the style again
self.view.makeToast("This is a full width piece of toast", duration: 3.0, position: .Bottom, style: nil)
```

**Comment by scalessec** [comment]
A caveat here though, is that it will only be full width if you have enough content to fill the width. If you want it to always be full width even if there's only a few words, then you'd have to use a custom view that is always the width of the screen.

**Comment by mitchellporter** [comment]
Hey Charles,

Already read the documentation, but like you mentioned it won't work properly if you do not provide enough text. I just finished using my own custom view and it works perfectly.

Thanks for putting this library together for us.

Cheers.
