### ISSUE TITLE
Cocoapod Migration

### ISSUE THREAD

**Issue by dpfannenstiel** [scalessec/Toast-Swift#41]
Working on my new release I have modified my podfile to request the Swift 3 branch.  After running pod install, Xcode attempts to migrate Toast.swift to use the new access control identifiers "open" and "fileprivate".

**Comment by scalessec** [comment]
The current `2.0.0` branch has full for Swift 3 and Xcode 8 (this is also currently on `master`). However, please also see #38. The current release of CocoaPods is not compatible with Xcode 8 and therefore I can't publish the new pod until CocoPods 1.1.0 is released (hopefully this happens soon).

**Comment by dpfannenstiel** [comment]
Sorry to waste your time, I solved this another way.  The problem was with the pod file.  I needed to add a `post_install` hook to update the Swift Version to 3.0.  That prevents the manual migrations I was undergoing.

**Comment by yzhong52** [comment]
@dpfannenstiel interesting and would appreciate it if you can provide a little more detail of how you resolve the problem!

**Comment by arrrggghhh** [comment]
@yzhong52 I think what @dpfannenstiel used was this:

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0' # or '3.0'
    end
  end
end
```

But in my case, Toast-Swift fails to compile. I'm waiting for the new version of cocoapods.

**Comment by dpfannenstiel** [comment]
That is how I'm doing it.  And until cocoa pods issue is resolve I'm using
`   pod 'Toast-Swift', :git => 'https://github.com/scalessec/Toast-Swift.git', :branch => 'feature/swift-3.0' 
`
to get the correct version of the code.
