### ISSUE TITLE
Change documentation

### ISSUE THREAD

**Issue by arthuronoszko** [scalessec/Toast-Swift#45]
Hi!

I just wanted to let you know that in your documentation on your github page, it says:

```
// create a new style
let style = ToastStyle()

// this is just one of many style options
style.messageColor = UIColor.blue
```

This does not compile because style is a constant.
Can you change this to 

```
// create a new style
var style = ToastStyle()

// this is just one of many style options
style.messageColor = UIColor.blue
```

I know, this is a small detail, but I just wanted you to know

Thank you :)

BR
Arthur

**Comment by scalessec** [comment]
Good catch. Thanks.
