### ISSUE TITLE
Dont show duplicate message in toast

### ISSUE THREAD

**Issue by iad24** [scalessec/Toast-Swift#54]
Please consider this scenario:
1. I got a button and if user clicks it, it will show the toast message "Button clicked"
2. If I click it quickly like 5 times, it will also show the toast msg 5 times (one after the other)

Can we have an option that if it should NOT show the other queued toast message IF they have same string content with the current toast displayed and in period of time.
Lets say the show duration is 2 secs. If I clicked it 5 times within 2 secs, it will only show once.

**Comment by tigerraj32** [comment]
You can set your own singleton class variable to indicate toastActive and check every time before you display toast message.
```
        if AppData.shared.isToastActive == false{
            AppData.shared.isToastActive = true
            self.makeToast(message, style: style, completion: { (didTap) in
                AppData.shared.isToastActive = false
                if didTap {
                    Logger.debug(#function,"completion from tap")
                } else {
                    Logger.debug(#function,"completion without tap")
                }
            })
        }
```

**Comment by scalessec** [comment]
You should handle this yourself in your application in a manner that suits your need.
