### ISSUE TITLE
Linking issue when building with swift 3

### ISSUE THREAD

**Issue by felixswang** [scalessec/Toast-Swift#58]
This is the error message when building. Look at the bottom part please.

Ld /Users/felixwang/Library/Developer/Xcode/DerivedData/SatePartnerIOS-awzwcapidujzoagsdtwreyhzjzkp/Build/Products/Debug-iphonesimulator/SatePartnerIOS.app/SatePartnerIOS normal x86_64
    cd /Users/felixwang/Products/Sate/SatePartnerIOS
    export IPHONEOS_DEPLOYMENT_TARGET=9.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator10.2.sdk -L/Users/felixwang/Library/Developer/Xcode/DerivedData/SatePartnerIOS-awzwcapidujzoagsdtwreyhzjzkp/Build/Products/Debug-iphonesimulator -F/Users/felixwang/Library/Developer/Xcode/DerivedData/SatePartnerIOS-awzwcapidujzoagsdtwreyhzjzkp/Build/Products/Debug-iphonesimulator -F/Users/felixwang/Library/Developer/Xcode/DerivedData/SatePartnerIOS-awzwcapidujzoagsdtwreyhzjzkp/Build/Products/Debug-iphonesimulator/GTMSessionFetcher -F/Users/felixwang/Library/Developer/Xcode/DerivedData/SatePartnerIOS-awzwcapidujzoagsdtwreyhzjzkp/Build/Products/Debug-iphonesimulator/GoogleToolboxForMac -F/Users/felixwang/Library/Developer/Xcode/DerivedData/SatePartnerIOS-awzwcapidujzoagsdtwreyhzjzkp/Build/Products/Debug-iphonesimulator/Toast-Swift -F/Users/felixwang/Products/Sate/SatePartnerIOS/Pods/FirebaseAnalytics/Frameworks/frameworks -F/Users/felixwang/Products/Sate/SatePartnerIOS/Pods/FirebaseAuth/Frameworks/frameworks -F/Users/felixwang/Products/Sate/SatePartnerIOS/Pods/FirebaseCore/Frameworks -F/Users/felixwang/Products/Sate/SatePartnerIOS/Pods/FirebaseDatabase/Frameworks -F/Users/felixwang/Products/Sate/SatePartnerIOS/Pods/FirebaseInstanceID/Frameworks/frameworks -F/Users/felixwang/Products/Sate/SatePartnerIOS/Pods/GoogleInterchangeUtilities/Frameworks/frameworks -F/Users/felixwang/Products/Sate/SatePartnerIOS/Pods/GoogleSymbolUtilities/Frameworks/frameworks -filelist /Users/felixwang/Library/Developer/Xcode/DerivedData/SatePartnerIOS-awzwcapidujzoagsdtwreyhzjzkp/Build/Intermediates/SatePartnerIOS.build/Debug-iphonesimulator/SatePartnerIOS.build/Objects-normal/x86_64/SatePartnerIOS.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=9.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/felixwang/Library/Developer/Xcode/DerivedData/SatePartnerIOS-awzwcapidujzoagsdtwreyhzjzkp/Build/Intermediates/SatePartnerIOS.build/Debug-iphonesimulator/SatePartnerIOS.build/Objects-normal/x86_64/SatePartnerIOS_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-link-runtime -L/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/swift/iphonesimulator -Xlinker -add_ast_path -Xlinker /Users/felixwang/Library/Developer/Xcode/DerivedData/SatePartnerIOS-awzwcapidujzoagsdtwreyhzjzkp/Build/Intermediates/SatePartnerIOS.build/Debug-iphonesimulator/SatePartnerIOS.build/Objects-normal/x86_64/SatePartnerIOS.swiftmodule -ObjC -lc++ -licucore -lsqlite3 -lz -framework AddressBook -framework CFNetwork -framework FirebaseAnalytics -framework FirebaseAuth -framework FirebaseCore -framework FirebaseDatabase -framework FirebaseInstanceID -framework GTMSessionFetcher -framework GoogleInterchangeUtilities -framework GoogleSymbolUtilities -framework GoogleToolboxForMac -framework Security -framework StoreKit -framework SystemConfiguration -framework Toast_Swift -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/felixwang/Library/Developer/Xcode/DerivedData/SatePartnerIOS-awzwcapidujzoagsdtwreyhzjzkp/Build/Intermediates/SatePartnerIOS.build/Debug-iphonesimulator/SatePartnerIOS.build/SatePartnerIOS.app.xcent -framework Pods_SatePartnerIOS -Xlinker -dependency_info -Xlinker /Users/felixwang/Library/Developer/Xcode/DerivedData/SatePartnerIOS-awzwcapidujzoagsdtwreyhzjzkp/Build/Intermediates/SatePartnerIOS.build/Debug-iphonesimulator/SatePartnerIOS.build/Objects-normal/x86_64/SatePartnerIOS_dependency_info.dat -o /Users/felixwang/Library/Developer/Xcode/DerivedData/SatePartnerIOS-awzwcapidujzoagsdtwreyhzjzkp/Build/Products/Debug-iphonesimulator/SatePartnerIOS.app/SatePartnerIOS

ld: /Users/felixwang/Library/Developer/Xcode/DerivedData/SatePartnerIOS-awzwcapidujzoagsdtwreyhzjzkp/Build/Products/Debug-iphonesimulator/Toast_Swift.framework/Toast_Swift compiled with older version of Swift language (2.0) than previous files (3.0) for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by scalessec** [comment]
`Toast_Swift compiled with older version of Swift language (2.0) than previous files (3.0) for architecture x86_64`

You compiled the pod with the Swift 2.x compiler, and you're trying to use it in a Swift 3.x project. I don't use CocoaPods personally, so I'm not sure of the exact fix but I don't believe there's anything wrong with the library. Make sure you're using the latest tag for Swift 3.
