### ISSUE TITLE
Cannot find the right reference for makeToast() method

### ISSUE THREAD

**Issue by felixswang** [scalessec/Toast-Swift#59]
Just upgraded the codebase to use Swift 3 and Toast-Swift has stopped working for me.

If I use

```
self.view.makeToast(
            "Update partner information failed. Please try again.",
            duration: 3.0,
            position: .Center)
```

it complains: Ambiguous reference to member 'makeToast(_:duration:position:)'

If I use

```
self.view.makeToast(
            message: "Update partner information failed. Please try again.",
            duration: 3.0,
            position: .Center)
```

it complains: Argument labels '(message:, duration:, position:)' do not match any available overloads

What is the right way to call makeToast()?

Thanks!

**Comment by scalessec** [comment]
Enums in Swift 3 start with a lower case letter. It's `.center`. Please look at the demo project and README before opening more tickets like this.
