### ISSUE TITLE
Dismiss a Toast or all Toasts?

### ISSUE THREAD

**Issue by smart-fun** [scalessec/Toast-Swift#61]
Hello,

is there a way to dismiss one given toast or all toasts?

I am using toasts in a TableView. Every time I click an item to add it in my favorite items, I display a toast "item added to favorites". The problem is that when I scroll down and views are recycled, I can see the toast on another item for a short moment (depending on the duration of the toast).

Do you see a way to fix this?

Thanks!

Arnaud.

**Comment by maxmika** [comment]
There's a function called `.removeAllToasts()` defined for all UIView objects. Maybe this is what you need?

**Comment by smart-fun** [comment]
Hello Max and thank you for your answer,

this is probably what I need, but I can't find such a function.

I looked into the Toast.swift file (both locally and in github), I searched in all files from xcode, tried auto-completion, but can't find it :/

I am using:
pod 'Toast-Swift', '~> 2.0.0'

Is this the correct version? What did I miss?

thanks again,

Arnaud.

**Comment by maxmika** [comment]
Can you see the `hideToastActivity(...)`func? If yes, you can pass them the respective UIView you created the toast on and voila - toast's gone.
