### ISSUE TITLE
When displaying the toast in a table view controller, it always shows beneath the table headers

### ISSUE THREAD

**Issue by SnitramDev** [scalessec/Toast-Swift#67]
When displaying the toast in a table view controller, it always shows beneath the table headers (the toast is cut off by the table headers).

**Comment by scalessec** [comment]
Display the toast in a different view then. Perhaps a parent view or the window? This is not an issue with the library.

**Comment by saxahan** [comment]
> Display the toast in a different view then. Perhaps a parent view or the window? This is not an issue with the library.

Nope, even on the top most window, it shows behind avplayer layer or something.
