### ISSUE TITLE
ToastPosition.top not showing toast

### ISSUE THREAD

**Issue by Nidhee** [scalessec/Toast-Swift#68]
Hello,

I want to show toast on top of screen and doing like this,

 `self.view.makeToast("Toast", duration: 1.0, position: ToastPosition.top)`

but it is not showing toast. When I change position to center or bottom it shows toast. 

I have Toast-Swift, 1.4.0

**Comment by waleedAlmubarak** [comment]
Had the issue here.

I fixed it by using:

`self.tabBarController?.view.makeToast("Your message here", duration: 30.0, position: ToastPosition.top)`

**Comment by scalessec** [comment]
This is not a bug in the library. The toast will be presented in your view's frame, wherever that may be.
