### ISSUE TITLE
When controller's tabBar is NOT hidden, toast is showing underneath tabbar.

### ISSUE THREAD

**Issue by Benyi-Peng** [scalessec/Toast-Swift#69]
Suggest: Make the position a little bit higher ,when `enum ToastPosition` is set to bottom

**Comment by jerydarkside** [comment]
If in your app, you only show toasts at the bottom, you can use
ToastManager.shared.style.verticalPadding to systematically increase the padding.

Concerning the Toast-Swift library, a possible evolution could be to replace
ToastManager.shared.style.verticalPadding
by
ToastManager.shared.style.bottomPadding
ToastManager.shared.style.topPadding

If I have time, I will make a merge request for that.

**Comment by scalessec** [comment]
This is not for the library to handle. You can display the Toast wherever you like, so your application should position it above the tab bar if that's what you want. Alternatively, you can display it in the tab controller's view and it will appear on top of the tab bar.

**Comment by Benyi-Peng** [comment]
Thanks for reply.^_^
