### ISSUE TITLE
hideAllToasts() not inclueded when installing by CocoaPods

### ISSUE THREAD

**Issue by cafedeichi** [scalessec/Toast-Swift#75]
Seemingly hideAllToasts() is not included in Toast.swift when installing by CocoaPods.
Hoping it'll be updated soon.

**Comment by scalessec** [comment]
I'll be publishing a new tag for Cocoapods once Swift 4 hits gold master. There won't be an update for Swift 3.

**Comment by cafedeichi** [comment]
Gee, Okay thx.
