### ISSUE TITLE
self.view.hideAllToasts()

### ISSUE THREAD

**Issue by sebastiaoRealino** [scalessec/Toast-Swift#79]
Hide all toasts does not work. This method does not exist anymore.

**Comment by bjbae** [comment]
I have same problem. There is a hideAllToasts in downloaded source, but not exist in Carthage.

**Comment by scalessec** [comment]
This is not in any current tags. It's currently on the `master` branch and will be available to Carthage and CocoaPods after the GM of iOS11 / Swift 4 is released.

**Comment by babkouew** [comment]
Hide all toasts still doesn't work. Any update on the issue?
