### ISSUE TITLE
Toast Message not getting displayed when clicked more than once.

### ISSUE THREAD

**Issue by kushagra21** [scalessec/Toast-Swift#80]
We are working on a project , where we need to display error messages to the users and toast-swift appeared to be a decent library for this purpose. The issue which i'm facing is that the message is not getting displayed more than once if the button is clicked more than once after some time interval. but if reload the view controller it's again showing once and then again the same thing.

We are using the basic usage function in our entire app and using version 2.0.0

self.view.makeToast("Some message", duration: 1.0, position: .bottom)

**Comment by rob-keepsafe** [comment]
It's because the queueing mechanism doesn't work. An easy test case is to create a queue of toasts in a for loop and see that none of them show.

**Comment by scalessec** [comment]
@kushagra21  @rob-keepsafe I have no idea what either of you guys are talking about.

@kushagra21 Sound like you're presenting the same message directly on top of the previous message. That's your mistake, not the library's. Either position subsequent messages elsewhere, or hide the first message before showing the subsequent.

@rob-keepsafe The queuing mechanism works perfectly fine.

This code displays 10 toasts, one after the other, when `ToastManager.shared.isQueueEnabled` is `true`. When `false`, it produces all 10 immediately directly on top of each other:
```swift
for _ in 0...9 {
     // Make toast with a duration and position
     // self.navigationController?.view.makeToast("This is a piece of toast", duration: 1.0, position: .bottom)
}

Additionally you can display and position the toast views in any view in your hierarchy. Whether that be `self.view`, `self.navigationController.view`, `myCustomView`, or even directly in the window with `self.view.window`. It's up to the programmer using the library to institute some common sense as to what works best for their own application.
