### ISSUE TITLE
Swift 4 XCode 9

### ISSUE THREAD

**Issue by BurhanMughal** [scalessec/Toast-Swift#83]
- 2 issues in this pod. 
- Can't use it anymore.

1-  Argument of '#selector' refers to instance method 'toastTimerDidFinish' that is not exposed to Objective-C
2- Argument of '#selector' refers to instance method 'handleToastTapped' that is not exposed to Objective-C 

Can you please tell when 3.0.0 will be available ?
Thanks for your good work :)

**Comment by scalessec** [comment]
Hey @BurhanMughal, I’m on holiday through the end of this week. I’ll commit to getting the `3.0.0` release out sometime next week. Sorry for the delay.

**Comment by razvandub** [comment]
+1 thanks.

**Comment by razvandub** [comment]
@scalessec when is 3.0.0 planned for release? Thanks.

**Comment by andrey-zelenin** [comment]
When the release is planned? Thanks

**Comment by gtgg** [comment]
When the release is planned?

**Comment by scalessec** [comment]
So sorry for the delay. `master` is almost ready for a release. `3.0.0` will be published this weekend.

**Comment by scalessec** [comment]
`3.0.0` tag is live via Carthage and Manual installation. I haven't published a new pod yet due to issues with CocoaPods, but I'll resolve that this weekend.

**Comment by scalessec** [comment]
`3.0.0` has been published to CocoaPods.

**Comment by andrey-zelenin** [comment]
Great work, thanks

**Comment by hemaks777** [comment]
Hi,

How can I disable the background when toast is shown?Kindly reply with a solution.

**Comment by scalessec** [comment]
@hemaks777 Please use stackoverflow or the Apple Developer Forum to ask questions like this. Please don't use the issues here.

That being said, something like this should work for you:
```swift
self.view.isUserInteractionEnabled = false
self.view.makeToast("Hello world") { [weak self] _ in 
    self.view.isUserInteractionEnabled = true
}
```
