### ISSUE TITLE
Toast message shows behind Tab Bar Navigation in feature/Swift-4 branch

### ISSUE THREAD

**Issue by fahey252** [scalessec/Toast-Swift#87]
When showing a toast message with position bottom, if the view is within a tab bar navigator, the message shows behind the tab bar/cant see it.  When a toast message is shown for a view within a tab bar navigator, the message show should above the tab bar navigator.

**Comment by scalessec** [comment]
It's your responsibility to position the Toast where it makes sense for your UI. If you want the toast on top of the tab bar, present it in the tab bar controller's view (eg: `self.tabBarController?.view.makeToast("foo")`), otherwise you need to position the toast manually using `makeToast:point:`.
