### ISSUE TITLE
Toast goes under StatusBar or NavigationBar

### ISSUE THREAD

**Issue by hashemp206** [scalessec/Toast-Swift#90]
Thanks for developing this handy toast library

there is a problem when making toast at position top, 

`UIApplication.shared.keyWindow?.makeToast(message, duration: ToastManager.shared.duration, position: .top)`

toast will goes beneath statusBar

or when using ViewController view, embedded in `UINavigationController`, toast will goes beneath navigationBar.

is there any way overcome these issues?

<img width="368" alt="screen shot 2017-12-06 at 11 16 22 am" src="https://user-images.githubusercontent.com/3206748/33650386-05ee628c-da77-11e7-8cb4-9d3136cf59fd.png">

**Comment by scalessec** [comment]
You can position the toast wherever you want using `makeToast:duration:point:`. If you want it below the status bar, position it below the status bar. Same with the navigation bar.
