### ISSUE TITLE
Toast position not calculated properly when scroll offset

### ISSUE THREAD

**Issue by eoy4** [scalessec/Toast-Swift#91]
For some reason this started happening, I hadn't noticed before I updated to latest. Whenever I am on a tableview or scrollview and have scrolled down any amount of offset, when I show a toast it gets calculated as if the scroll offset were 0, so it appears way above, most of the time off-screen.  To get around this I have to start defining my toasts as self.navigationController?.view.makeToast("some"). This is an ugly workaround and I'm afraid it won't work as a generic solution to my global notifications solution. Can something be done to fix this?

**Comment by scalessec** [comment]
Toast can be presented inside any view in the hierarchy. It is completely agnostic to the superview and it has always worked that way. If you present it in a `UIScrollView` or one of it's subclasses (like `UITableView` or `UICollectionView`) it's going to scroll when the content scrolls just like any other view added to a scroll view. If you don't want your toast to scroll, don't present it in a scroll view. That's your responsibility, not the library's. 

FWIW, I've always disliked how the stock UITableViewController is configured by default such that `self.view === self.tableView`. There are many valid reasons when you want content to appear on top of a scroll view without scrolling. For this reason, I create my own `TableViewController` subclasses in my personal projects that add a `UITableView` instance as a subview of `self.view`. Same for `UICollectionViewController`. With this setup, presenting in `self.view` would work as you would like. You should decide what's right for you project.
