### ISSUE TITLE
Toast will be hidden by keyboard

### ISSUE THREAD

**Issue by RadicalTeam** [scalessec/Toast-Swift#96]
I use the toast to show error message when user inputing something. But this toast won't show only when i dismiss keyboard.

**Comment by ShengJunDong89** [comment]
Keyboard lives on a separate UIWindow, so when keyboard is shown, it will be on top of the current window, where your UI lives. I believe you can create a new UIWindow and have your toast shown on that instead. I have not test this, it's based on my knowledge of the view hierarchy. Hope it helps.

**Comment by Diogo72** [comment]
I think we can't create a UIWindow above the keyboard since iOS 11. As a workaround, I did this

`let windows = UIApplication.shared.windows

windows.last?.makeToast("toast message")
`

**Comment by scalessec** [comment]
This is up to you to decide where to present the toast. This is not an issue with the library.

**Comment by fukemy** [comment]
still covered by keyboard now, im using https://github.com/nathantannar4/InputBarAccessoryView
