### ISSUE TITLE
Allow customisation of activityIndicatorStyle

### ISSUE THREAD

**Issue by mobru** [scalessec/Toast-Swift#97]
The current UIActivityIndicatorView style is hard coded to be `.whiteLarge` (Toast.swift, `createToastActivityView()`, line 326). It would be nice to be able to customise this!

**Comment by 1149863953** [comment]
建议设计更多的个性化设置项，使用时可以根据个人喜好设置UIActivityIndicatorView的样式及ToastActivity的size

**Comment by Zeglaty** [comment]
is there any updates on this topic
