### ISSUE TITLE
Deprecation warning when using Swift 4

### ISSUE THREAD

**Issue by NickGaens** [scalessec/Toast-Swift#98]
>~/.../Pods/Toast-Swift/Toast/Toast.swift:222:22: 'flatMap' is deprecated: Please use compactMap(_:) for the case where closure returns an optional value

Xcode 9.3 beta 4, Toast-Swift 3.0.1.

**Comment by Kaspik** [comment]
Fixed - https://github.com/scalessec/Toast-Swift/pull/103
