### ISSUE TITLE
#No such module 'Toast_Swift'

### ISSUE THREAD

**Issue by sagarsukode** [scalessec/Toast-Swift#99]
Hi,
I am using this in Swift 4 and XCode 9.2.
While Archiving showing error "No such module 'Toast_Swift'".
But, while running/building project no error comes.
Please check bellow screenshot for more details and please help me out in this.
Thanks....

![screen shot 2018-03-16 at 11 02 02 am](https://user-images.githubusercontent.com/15633194/37505269-f4192632-2909-11e8-9282-8a04d5b61a98.png)

**Comment by Chem-Lab** [comment]
Same issue here!

**Comment by ddralves** [comment]
Same problem here

**Comment by vovkaprigarin** [comment]
+1

**Comment by modusV** [comment]
+1

**Comment by 282144757** [comment]
+1

**Comment by mvpscottjon** [comment]
watch out your Swift & xcode version

the document says : 
Version 4.x.x requires Swift 4.2 and Xcode 10.
Version 3.x.x requires Swift 4 and Xcode 9.

so if you just Swift 4 , you should install  toast version 3.x.x

**Comment by ZackDT** [comment]
+1

**Comment by kebsont** [comment]
If you install with cocoa pod, you have to add the pod line in the podfile , import the module,  comment that line and close xcode before to run the pod install command.

After installation, open xcode and decomment the import line.

**Comment by satishVekariya** [comment]
`no such module 'Toast_Swift'`

`import Toast_Swift`
                                          ^

```
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal armv7
	CompileSwiftSources normal arm64 com.apple.xcode.tools.swift.compiler
	CompileSwift normal arm64
(3 failures)```

**Comment by zishanj** [comment]
This is no need to import it. It is developed as an extension of `UIView`. Simply call `view.makeToast()`.

**Comment by zishanj** [comment]
Its working with v5.0.0
